name: Release Drafter
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
