name: Release
on:
  release:
    types:
     - published

jobs:
  release-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      # pnpm should be preinstalled before the setup-node action
      # https://github.com/actions/setup-node/issues/530#issuecomment-1169317505
      - name: Install dependencies
        run: pnpm install

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Build
        run: pnpm build

      - name: Release to NPM Registry
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: "https://npm.pkg.github.com"

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
